imports:
    - php
    
tools:
    # php_changetracking: true 
    # php_sim:
    #    min_mass: 30
    # php_code_sniffer:
    #     config:
    #         standard: "WordPress" 
    # php_cpd: true
    php_hhvm: 
        filter:
            excluded_paths: ["src/wp-admin/includes/class-ftp*", "src/wp-admin/includes/class-pclzip.php", "src/wp-content/*", "src/wp-includes/ID3/*", "src/wp-includes/SimplePie/*", "src/wp-includes/Text/*", "src/wp-includes/atomlib.php", "src/wp-includes/class-IXR.php", "src/wp-includes/class-json.php", "src/wp-includes/class-phpass.php", "src/wp-includes/class-phpmailer.php", "src/wp-includes/class-pop3.php", "src/wp-includes/class-smtp.php", "src/wp-includes/class-snoopy.php", "src/wp-includes/kses.php", "src/wp-includes/rss.php"]
    # php_mess_detector: true
    # php_pdepend: true
    # php_analyzer: true          
    